from pathlib import Path


# RAIZ DO PROJETO
PROJECT_ROOT = Path(__file__).resolve().parents[2]


# DADOS
DATA_RAW_DIR = PROJECT_ROOT / "data_raw"

ENERGY_ZIP_PATH = DATA_RAW_DIR / "electricityloaddiagrams20112014.zip"


# RESULTADOS
RESULTS_DIR = PROJECT_ROOT / "results"

RESULTS_EXPLORATION_DIR = RESULTS_DIR / "exploration"
RESULTS_FEATURES_DIR = RESULTS_DIR / "features"
RESULTS_CLUSTERING_DIR = RESULTS_DIR / "clustering"
RESULTS_ANOMALIES_DIR = RESULTS_DIR / "anomalies"
RESULTS_MODELS_DIR = RESULTS_DIR / "models"
RESULTS_REALTIME_DIR = RESULTS_DIR / "realtime"

# Aliases mais curtos, caso queiras usar nos scripts
EXPLORATION_DIR = RESULTS_EXPLORATION_DIR
FEATURES_DIR = RESULTS_FEATURES_DIR
CLUSTERING_DIR = RESULTS_CLUSTERING_DIR
ANOMALIES_DIR = RESULTS_ANOMALIES_DIR
MODELS_DIR = RESULTS_MODELS_DIR
REALTIME_DIR = RESULTS_REALTIME_DIR


# RESULTADOS EM TEMPO REAL
ALERTS_DIR = RESULTS_REALTIME_DIR / "alerts"
PLOTS_DIR = RESULTS_REALTIME_DIR / "plots"
LOGS_DIR = RESULTS_REALTIME_DIR / "logs"
PREDICTIONS_DIR = RESULTS_REALTIME_DIR / "predictions"
ANALYSIS_DIR = RESULTS_REALTIME_DIR / "analysis"


# CACHE
BAZE_CACHE_DIR = RESULTS_DIR / "baze_cache"


# FICHEIROS ESPECÍFICOS
CLUSTERS_PATH = RESULTS_CLUSTERING_DIR / "clusters_cpe.csv"

ZIP_FALLBACK_PATH = (
    PROJECT_ROOT
    / "PM2025-TSAnomalyDetection"
    / "example-timeseries"
    / "consumo15m_11_2025.csv.zip"
)

INTERACTIVE_PCA_HTML = RESULTS_DIR / "interactive_pca_clusters.html"


# DASHBOARD
DASHBOARD_DIR = PROJECT_ROOT / "dashboard"
DASHBOARD_HTML = DASHBOARD_DIR / "dashboard.html"